"""New Migrations

Revision ID: 132554c0d96c
Revises: d8bf179d112d
Create Date: 2023-01-16 21:14:52.247061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132554c0d96c'
down_revision = 'd8bf179d112d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coffees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roasters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'roasters', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roasters', type_='unique')
    op.alter_column('roasters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
