"""new revision

Revision ID: 1f16103f2d49
Revises: 4810d7465aaa
Create Date: 2023-01-24 19:00:37.831686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f16103f2d49'
down_revision = '4810d7465aaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
