"""New Migrations

Revision ID: 25eb3b0df054
Revises: 44c66e8be271
Create Date: 2023-01-16 23:27:58.007894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25eb3b0df054'
down_revision = '44c66e8be271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
