"""New Migrations

Revision ID: 44c66e8be271
Revises: 132554c0d96c
Create Date: 2023-01-16 22:11:20.873345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c66e8be271'
down_revision = '132554c0d96c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coffees', 'roast',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('roasters_name_key', 'roasters', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roasters_name_key', 'roasters', ['name'])
    op.alter_column('coffees', 'roast',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
